# Site Settings
baseurl: ""

# Blog Setting
blog: False

# Language of the website
lang: en

# Search engine optimization settings
title: Nouamane Arhachoui
tagline: Computer Science Student
description: MSc Student in the Computer Science program of Institut Polytechnique de Paris
author: Nouamane Arhachoui
twitter:
  username: 
  card: 
logo: /assets/img/me.jpg
social:
  name: Nouamane Arhachoui
  links:
    - https://linkedin.com/in/nouamane-arhachoui
    - https://github.com/NouamaneA
locale: en_GB

# Page Settings
theme_settings:
  title: Grape Academic Theme

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  first_name: [Nouamane, N.]
  last_name: Arhachoui
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website, preprint] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
